=== fkalyousefi/cse445-a4/Hotels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="Hotels">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Hotel" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string"/>
              <xs:element name="Phone" type="phoneType" maxOccurs="unbounded"/>
              <xs:element name="Address" type="addressType"/>
            </xs:sequence>
            <!-- Optional attribute on Hotel -->
            <xs:attribute name="Rating" type="xs:decimal" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="addressType">
    <xs:sequence>
      <xs:element name="Number" type="xs:string"/>
      <xs:element name="Street" type="xs:string"/>
      <xs:element name="City" type="xs:string"/>
      <xs:element name="State" type="xs:string"/>
      <xs:element name="Zip" type="xs:string"/>
      <xs:element name="NearestAirport" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="phoneType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <!-- Required attribute so we can trigger Q1.3(2) by removing it in the error file -->
        <xs:attribute name="primary" type="xs:boolean" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== fkalyousefi/cse445-a4/Hotels.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hotels xmlns="http://cse445.edu/xml"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://cse445.edu/xml https://fkalyousefi.github.io/cse445-a4/Hotels.xsd">

  <Hotel id="H1" Rating="4.2">
    <Name>Westin Tempe</Name>
    <Phone>480-968-8885</Phone>
    <Phone>800-937-8461</Phone>
    <Address>
      <Number>11</Number>
      <Street>E 7th St</Street>
      <City>Tempe</City>
      <State>AZ</State>
      <Zip>85281</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H2" Rating="4.5">
    <Name>Hilton Garden Inn Phoenix Downtown</Name>
    <Phone>602-343-0006</Phone>
    <Address>
      <Number>15</Number>
      <Street>E Monroe St</Street>
      <City>Phoenix</City>
      <State>AZ</State>
      <Zip>85004</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H3" Rating="4.1">
    <Name>Hyatt Place Tempe</Name>
    <Phone>480-804-9544</Phone>
    <Address>
      <Number>730</Number>
      <Street>S Mill Ave</Street>
      <City>Tempe</City>
      <State>AZ</State>
      <Zip>85281</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H4">
    <Name>Courtyard Phoenix Downtown</Name>
    <Phone>602-555-1111</Phone>
    <Address>
      <Number>132</Number>
      <Street>S Central Ave</Street>
      <City>Phoenix</City>
      <State>AZ</State>
      <Zip>85004</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H5" Rating="4.3">
    <Name>Kimpton Hotel Palomar Phoenix</Name>
    <Phone>602-253-6633</Phone>
    <Address>
      <Number>2</Number>
      <Street>E Jefferson St</Street>
      <City>Phoenix</City>
      <State>AZ</State>
      <Zip>85004</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H6">
    <Name>Renaissance Phoenix Downtown Hotel</Name>
    <Phone>602-333-0000</Phone>
    <Address>
      <Number>100</Number>
      <Street>N 1st St</Street>
      <City>Phoenix</City>
      <State>AZ</State>
      <Zip>85004</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H7" Rating="4.0">
    <Name>Tempe Mission Palms</Name>
    <Phone>480-894-1400</Phone>
    <Address>
      <Number>60</Number>
      <Street>E 5th St</Street>
      <City>Tempe</City>
      <State>AZ</State>
      <Zip>85281</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H8">
    <Name>AC Hotel Phoenix Downtown</Name>
    <Phone>602-875-8000</Phone>
    <Address>
      <Number>414</Number>
      <Street>N 5th St</Street>
      <City>Phoenix</City>
      <State>AZ</State>
      <Zip>85004</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H9" Rating="4.2">
    <Name>Residence Inn Phoenix Downtown</Name>
    <Phone>602-603-2000</Phone>
    <Address>
      <Number>132</Number>
      <Street>S Central Ave</Street>
      <City>Phoenix</City>
      <State>AZ</State>
      <Zip>85004</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H10">
    <Name>Hyatt Regency Phoenix</Name>
    <Phone>602-252-1234</Phone>
    <Address>
      <Number>122</Number>
      <Street>N 2nd St</Street>
      <City>Phoenix</City>
      <State>AZ</State>
      <Zip>85004</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

  <Hotel id="H11" Rating="4.3">
    <Name>Canopy by Hilton Tempe Downtown</Name>
    <Phone>480-968-8880</Phone>
    <Address>
      <Number>108</Number>
      <Street>E University Dr</Street>
      <City>Tempe</City>
      <State>AZ</State>
      <Zip>85281</Zip>
      <NearestAirport>Phoenix Sky Harbor</NearestAirport>
    </Address>
  </Hotel>

</Hotels>
